version: 2
jobs:
  build:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
  nosetest:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: nosetests tests/math-test.py
  pytest:
    working_directoyr: ~/circleci-practice/tests
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: pytest