# job定義
jobs:
  build:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
  nosetest:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: nosetests tests/math-test.py
  pytest:
    working_directoyr: ~/circleci-practice/tests
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: pytest
# ワークフロー定義
workflows:
  version: 2
  build_and_test:
  # 実行するジョブを登録
    jobs:
      - build
      - nosetest
      - pytest