version: 2.1
# executor定義
executors:
  backend-executer:
    docker:
      - image: circleci/python:3.6.4
# commands定義
commands:
  # キャッシュ復元
  restore_python_package:
    steps:
      - restore_cache:
          name: Restore Python package
          key: deps-back-{{ .Branch }}-{{ checksum "requirements.txt" }}
  # キャッシュ保存
  save_python_package:
    steps: 
      - save_cache: # ** 依存関係キャッシュを保存する特別なステップ **
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/circleci-practice/src/__pycache__"
  # 依存関係を取得
  pip_install:
    steps:
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: which python
      - run:
          command: which pip
  # 検証1
  nosetest:
    steps:
      - run:
          command: nosetests tests/math-test.py
  # 検証2
  pytest:
    steps:
      - run:
          command: pytest

# job定義
jobs:
  backend_build:
    executor: backend-executer
    steps:
    - checkout
    - restore_python_package
    - pip_install
    - save_python_package
    - nosetest
    - pytest
  
# ワークフロー定義
workflows:
  backend-test:
  # 実行するジョブを登録
    jobs:
      - backend_build


