version: 2.1


# executor定義
executors:
  backend-executer:
    docker:
      - image: circleci/python:3.6.4
# commands定義
commands:
  # キャッシュ復元
  restore_python_package:
    steps:
      - restore_cache:
          name: Restore Python package
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
  # キャッシュ保存
  save_python_package:
    steps: 
      - save_cache: # ** 依存関係キャッシュを保存する特別なステップ **
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
  # 依存関係を取得
  pip_install:
    steps:
      # - checkout # プロジェクトのソースコードをworking_directoryで指定されたパスにチェックアウト
      # - restore_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: | # 仮想環境作成, 仮想環境をアクティベート, pip install
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      # - save_cache: # 仮想環境とインストールされたパッケージをキャッシュする
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #     paths:
      #       - ".venv" # キャッシュ先のPATH
      - run:
          name: run test
          command: |
            source .venv/bin/activate
            pytest tests

      
      
      
  # 検証1
  nosetest:
    steps:
      - run:
          command: nosetests tests/math-test.py
  # 検証2
  pytest:
    steps:
      - run:
          command: pytest

# job定義
jobs:
  backend_build:
    executor: backend-executer
    steps:
    - checkout
    - restore_python_package
    - pip_install
    - save_python_package
    # - nosetest
    # - pytest
  
# ワークフロー定義
workflows:
  backend-test:
  # 実行するジョブを登録
    jobs:
      - backend_build