version: 2.1


executors:
  backend-executer:
    docker:
      - image: circleci/python:3.6.4

commands:
  restore_python_package:
    steps:
      - restore_cache:
          name: Restore Python package
          keys: 
            - deps-back-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - deps-back-
  save_python_package:
      - save_cache: # ** 依存関係キャッシュを保存する特別なステップ **
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/circleci-practice/src/__pycache__"
  pip install:
    steps:
      - run:
          command: sudo pip install -r requirements.txt
  nosetest:
    steps:
      - run:
          command: nosetests tests/math-test.py
  pytest:
    working_directoyr: ~/circleci-practice/tests
    steps:
      - run:
          command: pytest

# job定義
jobs:
  backend_build:
    executor: backend-executer
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
    - restore_python_package
    - pip_install
    - save_python_package
    - nosetest
    - pytest
  
# ワークフロー定義
workflows:
  version: 2.1
  backend-test:
  # 実行するジョブを登録
    jobs:
      - backend_build
      - pip_install
      - nosetest:
          requires:
            - pip_install
      - pytest:
          requires:
            - pip_install