version: 2.1
executors:
  test-executor:
    docker:
      - image: circleci/python:3.6.4 # 仮想環境を定義、dockerが使われることがほとんど
jobs:
  test_by_nosetest:
    executor: test-executor
    # docker:
    #   - image: circleci/python:3.6.4 # 仮想環境を定義、dockerが使われることがほとんど
    steps:
      - checkout # コードをレポジトリからチェックアウト
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: nosetests tests/math-test.py
  test_by_pytest:
    executor: test-executor
    # docker:
    #   - image: circleci/python:3.6.4 # 仮想環境を定義、dockerが使われることがほとんど
    steps:
      - checkout # コードをレポジトリからチェックアウト
      - run:
          command: sudo pip install -r requirements.txt
      - run:
          command: pytest tests/test_math.py

  # build:
  #   working_directoyr: ~/python-ci 
  #   docker:　
  #     - image: circleci/python:3.6.4 # 仮想環境を定義、dockerが使われることがほとんど
  #   steps:
  #     - checkout # コードをレポジトリからチェックアウト
  #     - run:
  #         command: sudo pip install -r requirements.txt
  #     - run:
  #         command: nosetests tests/math-test.py

workflows:
  test_workflow:
    jobs:
      - test_by_nosetest
      - test_by_pytest