# job定義
jobs:
  build:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
  test_setup:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: sudo pip install -r requirements.txt
      - save_cache: # ** 依存関係キャッシュを保存する特別なステップ **
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/circleci-practice/src/__pycache__"
  nosetest:
    working_directoyr: ~/circleci-practice
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache: # ** 依存関係キャッシュを保存する特別なステップ **
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "~/circleci-practice/src/__pycache__"
      # - run:
      #     command: sudo pip install -r requirements.txt
      - run:
          command: nosetests tests/math-test.py
  pytest:
    working_directoyr: ~/circleci-practice/tests
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      # - run:
      #     command: sudo pip install -r requirements.txt
      - run:
          command: pytest
# ワークフロー定義
workflows:
  version: 2
  build_and_test:
  # 実行するジョブを登録
    jobs:
      - build
      - test_setup:
          # 依存関係を定義 
          requires:
            - build
      - nosetest:
          requires:
            - test_setup
      - pytest:
          requires:
            - test_setup